const products = [
    {
        id: 1,
        name: "Quantum Sound X1",
        price: 299,
        originalPrice: 349,
        category: "Electronics",
        rating: 4.8,
        reviews: 312,
        badge: "Best Seller",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800",
        description: "Experience studio-quality audio with active noise cancellation and 40-hour battery life. Designed for comfort and pure sound immersion with premium drivers delivering crystal-clear highs and deep, powerful bass.",
        features: ["Active Noise Cancellation", "40-hour Battery Life", "Bluetooth 5.2", "Foldable Design"]
    },
    {
        id: 2,
        name: "Luxe Chronograph",
        price: 189,
        originalPrice: 220,
        category: "Accessories",
        rating: 4.5,
        reviews: 198,
        badge: null,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800",
        description: "A timeless masterpiece featuring sapphire crystal glass and premium Italian leather straps. Water-resistant up to 50 metres, this chronograph blends heritage craftsmanship with modern precision.",
        features: ["Sapphire Crystal", "50m Water Resistant", "Italian Leather Strap", "Swiss Movement"]
    },
    {
        id: 3,
        name: "Pixel View 4K Monitor",
        price: 450,
        originalPrice: 499,
        category: "Electronics",
        rating: 4.7,
        reviews: 445,
        badge: "New",
        image: "https://images.unsplash.com/photo-1552308995-2baac1ad5490?q=80&w=800",
        description: "4K UHD display with 144Hz refresh rate and IPS panel. Perfect for creators and gamers demanding colour accuracy, fluid motion, and wide viewing angles.",
        features: ["4K UHD Resolution", "144Hz Refresh Rate", "IPS Panel", "HDMI 2.1 & DisplayPort"]
    },
    {
        id: 4,
        name: "Arc Mechanical Keyboard",
        price: 135,
        originalPrice: 135,
        category: "Electronics",
        rating: 4.6,
        reviews: 261,
        badge: null,
        image: "https://images.unsplash.com/photo-1561112078-7d24e04c3407?q=80&w=800",
        description: "Tactile typing redefined. Hot-swappable switches, per-key RGB lighting and a compact tenkeyless layout built for speed and precision.",
        features: ["Hot-Swap Switches", "Per-Key RGB", "TKL Layout", "USB-C Detachable Cable"]
    },
    {
        id: 5,
        name: "Zest Smart Water Bottle",
        price: 45,
        originalPrice: 60,
        category: "Lifestyle",
        rating: 4.6,
        reviews: 134,
        badge: "Sale",
        image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?q=80&w=800",
        description: "Self-cleaning bottle with built-in UV-C LED technology. Keeps liquids cold for 24 hours and hot for 12. Track hydration via the companion mobile app.",
        features: ["UV-C Self-Cleaning", "24h Cold / 12h Hot", "App Connected", "BPA Free"]
    },
    {
        id: 6,
        name: "Nordic Floor Lamp",
        price: 140,
        originalPrice: 140,
        category: "Home",
        rating: 4.4,
        reviews: 87,
        badge: null,
        image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=800",
        description: "Elegant Scandinavian design that brings warmth to any room. Adjustable brightness from warm to cool white, with height adjustment from 120–160cm.",
        features: ["Adjustable Brightness", "Warm to Cool White", "Height Adjustable", "Energy Saving LED"]
    },
    {
        id: 7,
        name: "Eco-Sole Runners",
        price: 110,
        originalPrice: 130,
        category: "Fashion",
        rating: 4.2,
        reviews: 320,
        badge: "Sale",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800",
        description: "Lightweight, breathable sneakers made from recycled ocean plastics. High-performance foam midsole absorbs impact while our carbon footprint offset programme goes the extra mile.",
        features: ["Recycled Materials", "Impact Foam Sole", "Breathable Upper", "Carbon Offset"]
    },
    {
        id: 8,
        name: "Solstice Sunglasses",
        price: 160,
        originalPrice: 160,
        category: "Accessories",
        rating: 4.5,
        reviews: 212,
        badge: null,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800",
        description: "Polarised lenses with hand-crafted acetate frames, providing full UV400 protection. Classic silhouette with a contemporary matte finish.",
        features: ["UV400 Protection", "Polarised Lenses", "Acetate Frames", "Soft Case Included"]
    },
    {
        id: 9,
        name: "Drift Wireless Mouse",
        price: 75,
        originalPrice: 90,
        category: "Electronics",
        rating: 4.6,
        reviews: 178,
        badge: null,
        image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=800",
        description: "Ergonomic vertical design scientifically proven to reduce wrist strain. Dual connectivity via Bluetooth or 2.4GHz USB dongle — cross-platform compatible.",
        features: ["Ergonomic Vertical Design", "Bluetooth & 2.4GHz", "70h Battery", "Cross-Platform"]
    },
    {
        id: 10,
        name: "Urban Explorer Jacket",
        price: 210,
        originalPrice: 250,
        category: "Fashion",
        rating: 4.7,
        reviews: 156,
        badge: "Best Seller",
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800",
        description: "Windproof and water-resistant outer shell with removable thermal lining. Multiple hidden zip pockets and reflective details keep you secure and visible after dark.",
        features: ["Windproof Shell", "Removable Thermal Lining", "Hidden Pockets", "Reflective Detailing"]
    },
    {
        id: 11,
        name: "Aroma Diffuser Pro",
        price: 55,
        originalPrice: 70,
        category: "Lifestyle",
        rating: 4.3,
        reviews: 99,
        badge: "Sale",
        image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?q=80&w=800",
        description: "Ultrasonic cool-mist diffuser with 7-colour ambient LED and auto shut-off. Runs up to 10 hours on a single fill. Transform any room into a calming sanctuary.",
        features: ["Ultrasonic Mist", "7-Colour LED", "10h Runtime", "Auto Shut-Off"]
    },
    {
        id: 12,
        name: "Canvas Tote Bag",
        price: 38,
        originalPrice: 38,
        category: "Fashion",
        rating: 4.1,
        reviews: 203,
        badge: null,
        image: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800",
        description: "Heavyweight waxed canvas with full leather trim and solid brass hardware. Fits a 15\" laptop; includes an internal zip organiser and key clip.",
        features: ["Waxed Canvas", "Leather Trim", "Fits 15\" Laptop", "Internal Organiser"]
    }
];
